# Generated by Django 2.2.12 on 2020-04-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_depan', models.CharField(max_length=30)),
                ('nama_belakang', models.CharField(max_length=20)),
                ('alamat', models.TextField()),
            ],
        ),
    ]
